language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

branches:
  only: master

os:
  - linux

before_script:
  - yarn install

after_failure:
  - cat /home/travis/build/joumenharzli/ngx-tools/npm-debug.log

cache:
  directories: node_modules

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - yarn run test && yarn run build
